language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

env:
  - SYMFONY_VERSION="2.7.*"
  - SYMFONY_VERSION="2.8.*"
  - SYMFONY_VERSION="3.4.*"
  - SYMFONY_VERSION="4.4.*"
  - SYMFONY_VERSION="5.0.*"

matrix:
  exclude:
    - php: 7.0
      env: SYMFONY_VERSION="4.4.*" # Symfony >= 4.0 PHP requirement is ^7.1.3
    - php: 7.0
      env: SYMFONY_VERSION="5.0.*" # Symfony >= 4.0 PHP requirement is ^7.1.3

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer selfupdate
  - if [ "$SYMFONY_VERSION" = "3.4.*" ] || [ "$SYMFONY_VERSION" = "4.4.*" ] || [ "$SYMFONY_VERSION" = "5.0.*" ]; then rm -f phpunit.xml; cp phpunit.sf4.xml.dist phpunit.xml; fi
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/framework-bundle:${SYMFONY_VERSION}" --no-update; fi;

install: COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install --prefer-dist --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email: eugone.yann@gmail.com
